### ISSUE TITLE
Team Management

### ISSUE THREAD

**Issue by ben-x-dev** [nbcp/firestarter-leaderboard#2]
Update TeamsService to allow lead to manage official member of the team.
He/she can perform the ff:
- [x] Rejecting would remove the player from the applications queue
- [x] Approving would remove player from the applications queue and add him/her to the team's array of members
- [x] Kicking out from the team would remove the member from the team's member list

We need:
- [x] Need a collection to store membership applications queue
- [x] members: array to store a list of official members of the team

Exact contents of Service:
- [x] Create new Membership
- [x] Approve Membership
- [x]  Delete Membership
- [x] Get Membership
- [x] Get TeamId of User
- [x] Find out if User is Lead
- [x] Get Team Members
- [x] Get Members for Approval

**Comment by fjgallard** [comment]
Currently having problems with login - cannot test the code I wrote. May have to consult with Ben and Gerard next week on what probably caused.

**Comment by fjgallard** [comment]
Fixed on Jomer_Branch, HEAD is at e660e7b, yet to merge with master
