### ISSUE TITLE
Team Lead Dashboard: List of Team Members

### ISSUE THREAD

**Issue by ben-x-dev** [nbcp/firestarter-leaderboard#3]
The team lead dashboard need to contain:
- [x] A list showing approved team members with their xp, season and career ranks 
   - Clicking a member would redirect to the member's profile
   - Button to kick out a member from the team
- [x] A list to view and approve/reject membership applications. Approving would add the player as an official member of the team

**Comment by fjgallard** [comment]
Current Todos: 

Mat-Table cannot handle empty rows yet
Various UI changes
No dashboard for non-leads

**Comment by ben-x-dev** [comment]
Closed by #17
