### ISSUE TITLE
Email Team Lead when Player requests join team

### ISSUE THREAD

**Issue by ben-x-dev** [nbcp/firestarter-leaderboard#52]
Email Team Lead with:
![image](https://user-images.githubusercontent.com/11013464/54800751-7bf97300-4c9e-11e9-979d-04a11c5b0bfe.png)

**Comment by fjgallard** [comment]
Where are we supposed to accessed lead email BTW? Should it be added to the teams collection?

**Comment by ben-x-dev** [comment]
nope, for now query from memberships collection, loop thru emails and send, until we figure out how to do better with mass email sending
