### ISSUE TITLE
Player Dashboard: List of Assigned Quests 

### ISSUE THREAD

**Issue by ben-x-dev** [nbcp/firestarter-leaderboard#6]
Update UserProfileComponent to also show:
- [x] player's quest along with their completion status and xp
- [x] Quest submission button for those they would submit for team lead approval.
- [x] Submission modal with quest info and field to supply date and link to completion proof that would show after hitting submit button
- [x] Email notification for team lead requesting quest approval

**Comment by ben-x-dev** [comment]
Quest validation depends on #5

**Comment by aronpadolina** [comment]
Note: 

We need to add the team lead email address in the player quest entities. This is to ease sending of email to the team lead when a player submits his/her quest for validation

Also, as per testing, the Email Service is not able to send out the emails

**Comment by ben-x-dev** [comment]
Closed by #19
